version: '3.8'

services:
  app:
    build: .
    container_name: droid-target-selection-app
    ports:
      - "6969:6969"
    depends_on:
      - mongodb
    environment:
      - PORT=6969
      - MONGODB_URI=mongodb://mongodb:27017/droid-target-selection
    volumes:
      - .:/app
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: droid-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: